// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermoFeatures;

namespace thermo_scrape.Migrations
{
    [DbContext(typeof(ThermoFeaturesDbContext))]
    [Migration("20190922220306_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ThermoFeatures.ThermostatLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Json");

                    b.Property<DateTimeOffset>("Stamp");

                    b.HasKey("Id");

                    b.ToTable("ThermostatLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
